# Generated by Django 3.2.6 on 2022-01-02 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0002_optical_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optical',
            old_name='profile_pic',
            new_name='frame_pic',
        ),
    ]
