# Generated by Django 3.2.6 on 2022-01-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0003_rename_profile_pic_optical_frame_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='optical',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
