# Generated by Django 3.2.6 on 2022-01-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0004_optical_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='optical',
            name='Eyes_checkup_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='optical',
            name='Glass_delivery_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='optical',
            name='Model_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1, null=True),
        ),
    ]
