# Generated by Django 3.2.6 on 2022-01-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0005_auto_20220102_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='optical',
            name='medal',
            field=models.CharField(blank=True, choices=[('Female', 'Female')], max_length=10),
        ),
    ]
