# Generated by Django 3.2.6 on 2022-01-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0006_optical_medal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optical',
            name='medal',
        ),
        migrations.AddField(
            model_name='optical',
            name='Gender_select',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
    ]
