# Generated by Django 3.2.6 on 2022-01-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0007_auto_20220102_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optical',
            name='Gender_select',
            field=models.IntegerField(verbose_name=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24')]),
        ),
    ]
