# Generated by Django 3.2.6 on 2022-01-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0008_alter_optical_gender_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='optical',
            name='customer_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='optical',
            name='Eyes_checkup_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='optical',
            name='Gender_select',
            field=models.IntegerField(verbose_name=(50, 51, 52, 53, 54, 55, 56, 57, 58, 59)),
        ),
        migrations.AlterField(
            model_name='optical',
            name='Glass_delivery_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='optical',
            name='frame_pic',
            field=models.ImageField(null=True, upload_to='profile_pic/DoctorProfilePic/'),
        ),
    ]
