# Generated by Django 3.2.6 on 2022-01-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0009_auto_20220110_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optical',
            name='Gender_select',
            field=models.IntegerField(verbose_name=(50, 51, 52, 53, 54, 55, 56, 57, 58, 59)),
        ),
        migrations.AlterField(
            model_name='optical',
            name='frame_pic',
            field=models.ImageField(null=True, upload_to='profile_pic/FramePic/'),
        ),
    ]
